name:
 pre-commit
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pre-commit
      uses: pre-commit/action@v3.0.0
