name:
 pre-commit
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pre-commit
      uses: pre-commit/action@v3.0.0
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply pre-commit changes
